spring:
  application:
    name: "monitoring-module"
  profiles:
    include: "h2"

management:
  server:
    port: 9092
  endpoints:
    web:
      exposure:
        include: "prometheus,health,beans"
server:
  tomcat:
    mbeanregistry:
      enabled: true