spring:
  application:
    name: "actuator-module"

management:
  server:
    port: 9092 # ??? ?? ?????? ?? ??? ???? ?????? ?? ??
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator" # ?????? ?? ??? /actuator? ??
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full

server:
  tomcat:
    mbeanregistry:
      enabled: true # ?? ???? ?? ????? ?? ??? ????.

# ??? ????? ?? ?? ???? ??
# https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.supported