spring:
  application:
    name: "actuator-module"

management:
  server:
    port: 9092 # Change the port to 9092 for Security
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator" # Change the base path to /actuator
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full

server:
  tomcat:
    mbeanregistry:
      enabled: true # Enable Tomcat Extra metrics

# https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.supported