spring:
  application:
    name: "actuator-module"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
